name: eurovista
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  connectivity_plus: ^5.0.2
  intl: ^0.17.0
  http: ^0.13.5
  path: ^1.8.3
  flutter_native_splash: ^2.3.7
  stacked: ^3.2.0
  dio: ^4.0.6
  logger: ^1.1.0
  stacked_services: ^0.9.7
  provider: ^6.1.1
  flutter_speed_dial: ^7.0.0
  fluttertoast: ^8.2.5
  mockito: ^5.0.17
#  flutter_native_splash: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_image.png
#    -
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_image.png
  color_dark: "#1a1a1a"
  image_dark: assets/images/splash_image.png

   add this
  android_12:
    icon_background_color: "#FFFFFF"
    image: assets/images/splash_image.png
    icon_background_color_dark: "#1a1a1a"
    image_dark: assets/images/splash_image.png